#SPDX-License-Identifier: Apache-2.0
---
all:
  children:
    routers:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ansible_playbook_python}}"

          router_hostname: "alma10-router"
          router_wan_interface: "enp1s0"
          router_lan_interface: "enp7s0"
          router_domain: "alma-testing.internal"
          router_lan_network: "192.0.2.1/24"

          dhcp_primary_dns: "86.54.11.1"
          dhcp_secondary_dns: "86.54.11.201"
          dhcp_client_pool_start: "192.0.2.100"
          dhcp_client_pool_end: "192.0.2.250"

